_wandb:
    value:
        cli_version: 0.23.1
        e:
            3ujul332an5kpe0etjetqhtekugmra3l:
                args:
                    - --arch
                    - resnet50x2
                    - --batch-size
                    - "256"
                    - --hf-datasets
                    - tsbpp/fall2025_deeplearning
                    - sm12377/tr_imgs:split=train
                    - --epochs
                    - "100"
                    - --exp-dir
                    - ./exp_interactive_debug
                    - --base-lr
                    - "0.2"
                    - --sim-coeff
                    - "25.0"
                    - --std-coeff
                    - "25.0"
                    - --cov-coeff
                    - "1.0"
                    - --num-workers
                    - "4"
                    - --enable-wandb
                    - --wandb-project
                    - vicreg-hf
                    - --wandb-name
                    - interactive-debug
                codePath: main_vicreg.py
                codePathLocal: main_vicreg.py
                cpu_count: 40
                cpu_count_logical: 40
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1282967031808"
                        used: "9950924800"
                email: sd6701@nyu.edu
                executable: /gpfs/data/shenlab/aj4718/miniconda3/envs/vicreg_hf/bin/python3.10
                git:
                    commit: 7d824f3716d574d0ad7e25dac5901faf44664fa5
                    remote: https://github.com/sd6701-droid/vicreg
                gpu: Tesla V100-SXM2-16GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Volta
                      cudaCores: 5120
                      memoryTotal: "17179869184"
                      name: Tesla V100-SXM2-16GB
                      uuid: GPU-da6ae732-4051-7957-9cc6-7fe76149a935
                host: gn-0022
                memory:
                    total: "404341198848"
                os: Linux-4.18.0-477.27.1.el8_8.x86_64-x86_64-with-glibc2.28
                program: /gpfs/data/shenlab/aj4718/vicreg/main_vicreg.py
                python: CPython 3.10.19
                root: exp_interactive_debug
                slurm:
                    cluster_name: slurm_cluster
                    conf: /etc/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00003C0000
                    cpu_bind_list: "0x00003C0000"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: system
                    job_cpus_per_node: "4"
                    job_end_time: "1765579800"
                    job_gid: "1024364111"
                    job_group: aj4718
                    job_id: "15064917"
                    job_name: bash
                    job_nodelist: gn-0022
                    job_num_nodes: "1"
                    job_partition: gpu4_long
                    job_qos: normal
                    job_start_time: "1764975000"
                    job_uid: "1024365920"
                    job_user: aj4718
                    jobid: "15064917"
                    launch_node_ipaddr: 192.168.0.102
                    localid: "0"
                    mem_per_node: "81920"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gn-0022
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "36529"
                    pty_win_col: "143"
                    pty_win_row: "34"
                    script_context: prolog_task
                    srun_comm_host: 192.168.0.102
                    srun_comm_port: "42377"
                    step_gpus: "2"
                    step_id: "0"
                    step_launcher_port: "42377"
                    step_nodelist: gn-0022
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /gpfs/data/shenlab/aj4718/vicreg
                    submit_host: bigpurple-ln2
                    task_pid: "4114227"
                    tasks_per_node: "1"
                    topology_addr: gn-0022
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                    umask: "0002"
                startedAt: "2025-12-05T23:35:05.673723Z"
                writerId: 3ujul332an5kpe0etjetqhtekugmra3l
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
            "2":
                - 1
                - 41
                - 49
                - 51
            "3":
                - 13
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
arch:
    value: resnet50x2
base_lr:
    value: 0.2
batch_size:
    value: 256
cov_coeff:
    value: 1
data_dir:
    value: /path/to/imagenet
device:
    value: cuda
dist_url:
    value: env://
distributed:
    value: false
enable_wandb:
    value: true
epochs:
    value: 100
exp_dir:
    value: exp_interactive_debug
hf_datasets:
    value:
        - tsbpp/fall2025_deeplearning
        - sm12377/tr_imgs:split=train
local_rank:
    value: -1
log_freq_time:
    value: 60
mlp:
    value: 8192-8192-8192
num_workers:
    value: 4
rank:
    value: 0
sim_coeff:
    value: 25
std_coeff:
    value: 25
wandb_api_key:
    value: 14abcf8b33d9a7f066dd1988891a00fec55f4030
wandb_entity:
    value: sd6701-new-york-university
wandb_name:
    value: interactive-debug
wandb_project:
    value: vicreg-hf
wd:
    value: 1e-06
world_size:
    value: 1
